// /*
//     Copyright (C) 2026 0x90d
//     This file is part of VideoDuplicateFinder
//     VideoDuplicateFinder is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     VideoDuplicateFinder is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
//     You should have received a copy of the GNU Affero General Public License
//     along with VideoDuplicateFinder.  If not, see <http://www.gnu.org/licenses/>.
// */
//

using System.Buffers.Binary;
using System.Text;

namespace VDF.Core.Utils {
	/// <summary>
	/// Decode-only reader for scan databases written by protobuf-net (VDF 3.x and
	/// early 4.x). Replaces the protobuf-net dependency for migration: new databases
	/// are written with MemoryPack, but legacy files must remain loadable — including
	/// under Native AOT, where protobuf-net's runtime type model does not work.
	///
	/// Implements exactly the wire encodings protobuf-net produced for our fixed
	/// schema: DatabaseWrapper { 1: varint Version, 2: repeated FileEntry,
	/// 3: varint ImageHashPipeline } plus the ancient pre-wrapper layout (a bare
	/// HashSet&lt;FileEntry&gt; at the root, entries as repeated field 1).
	/// DateTime/TimeSpan use protobuf-net's bcl.proto surrogate messages.
	/// Verified against golden files generated by protobuf-net itself.
	/// </summary>
	internal static class LegacyDatabaseReader {
		internal static DatabaseWrapper Read(ReadOnlySpan<byte> data) {
			var wrapper = new DatabaseWrapper { Version = 0, ImageHashPipeline = 0 };
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				switch (field) {
					case 1 when wire == 0: // DatabaseWrapper.Version
						wrapper.Version = (int)ReadVarint(data, ref pos);
						break;
					case 1 when wire == 2: // ancient bare-HashSet layout: entries at field 1
						wrapper.Entries.Add(ReadFileEntry(ReadLengthDelimited(data, ref pos)));
						break;
					case 2 when wire == 2:
						wrapper.Entries.Add(ReadFileEntry(ReadLengthDelimited(data, ref pos)));
						break;
					case 3 when wire == 0:
						wrapper.ImageHashPipeline = (int)ReadVarint(data, ref pos);
						break;
					default:
						SkipField(data, ref pos, wire);
						break;
				}
			}
			return wrapper;
		}

		static FileEntry ReadFileEntry(ReadOnlySpan<byte> data) {
			var entry = new FileEntry();
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				switch (field) {
					case 1 when wire == 2:
						entry._Path = ReadString(data, ref pos);
						break;
					case 2 when wire == 2:
						entry.Folder = ReadString(data, ref pos);
						break;
					case 3 when wire == 2: { // grayBytes pair
						var (key, bytes) = ReadDoubleBytesPair(ReadLengthDelimited(data, ref pos));
						entry.grayBytes[key] = bytes;
						break;
					}
					case 4 when wire == 2:
						entry.mediaInfo = ReadMediaInfo(ReadLengthDelimited(data, ref pos));
						break;
					case 5 when wire == 0:
						entry.Flags = (EntryFlags)ReadVarint(data, ref pos);
						break;
					case 6 when wire == 2:
						entry.DateCreated = ReadBclDateTime(ReadLengthDelimited(data, ref pos));
						break;
					case 7 when wire == 2:
						entry.DateModified = ReadBclDateTime(ReadLengthDelimited(data, ref pos));
						break;
					case 8 when wire == 0:
						entry.FileSize = (long)ReadVarint(data, ref pos);
						break;
					case 9 when wire == 2: { // PHashes pair
						var (key, value) = ReadDoubleUlongPair(ReadLengthDelimited(data, ref pos));
						entry.PHashes[key] = value;
						break;
					}
					case 10 when wire == 0: { // AudioFingerprint, unpacked
						entry.AudioFingerprint = Append(entry.AudioFingerprint, (uint)ReadVarint(data, ref pos));
						break;
					}
					case 10 when wire == 2: { // AudioFingerprint, packed
						var packed = ReadLengthDelimited(data, ref pos);
						int p = 0;
						var list = new List<uint>();
						while (p < packed.Length)
							list.Add((uint)ReadVarint(packed, ref p));
						entry.AudioFingerprint = entry.AudioFingerprint == null
							? list.ToArray()
							: Concat(entry.AudioFingerprint, list);
						break;
					}
					default:
						SkipField(data, ref pos, wire);
						break;
				}
			}
			if (entry._Path == null)
				throw new InvalidDataException("FileEntry without a path.");
			entry.Folder ??= string.Empty;
			return entry;
		}

		static (double key, byte[]? value) ReadDoubleBytesPair(ReadOnlySpan<byte> data) {
			double key = 0;
			byte[]? value = null; // absent value field = stored null
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				if (field == 1 && wire == 1)
					key = ReadDouble(data, ref pos);
				else if (field == 2 && wire == 2)
					value = ReadLengthDelimited(data, ref pos).ToArray();
				else
					SkipField(data, ref pos, wire);
			}
			return (key, value);
		}

		static (double key, ulong? value) ReadDoubleUlongPair(ReadOnlySpan<byte> data) {
			double key = 0;
			ulong? value = null;
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				if (field == 1 && wire == 1)
					key = ReadDouble(data, ref pos);
				else if (field == 2 && wire == 0)
					value = ReadVarint(data, ref pos);
				else if (field == 2 && wire == 1)
					value = ReadFixed64(data, ref pos);
				else
					SkipField(data, ref pos, wire);
			}
			return (key, value);
		}

		static MediaInfo ReadMediaInfo(ReadOnlySpan<byte> data) {
			var streams = new List<MediaInfo.StreamInfo>();
			TimeSpan duration = TimeSpan.Zero;
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				if (field == 1 && wire == 2)
					streams.Add(ReadStreamInfo(ReadLengthDelimited(data, ref pos)));
				else if (field == 2 && wire == 2)
					duration = ReadBclTimeSpan(ReadLengthDelimited(data, ref pos));
				else
					SkipField(data, ref pos, wire);
			}
			return new MediaInfo { Streams = streams.ToArray(), Duration = duration };
		}

		static MediaInfo.StreamInfo ReadStreamInfo(ReadOnlySpan<byte> data) {
			var s = new MediaInfo.StreamInfo();
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				switch (field) {
					case 1 when wire == 2: s.Index = ReadString(data, ref pos); break;
					case 2 when wire == 2: s.CodecName = ReadString(data, ref pos); break;
					case 3 when wire == 2: s.CodecLongName = ReadString(data, ref pos); break;
					case 4 when wire == 2: s.CodecType = ReadString(data, ref pos); break;
					case 5 when wire == 2: s.PixelFormat = ReadString(data, ref pos); break;
					case 6 when wire == 0: s.Width = (int)ReadVarint(data, ref pos); break;
					case 7 when wire == 0: s.Height = (int)ReadVarint(data, ref pos); break;
					case 8 when wire == 0: s.SampleRate = (int)ReadVarint(data, ref pos); break;
					case 9 when wire == 2: s.ChannelLayout = ReadString(data, ref pos); break;
					case 10 when wire == 0: s.BitRate = (long)ReadVarint(data, ref pos); break;
					case 11 when wire == 5: s.FrameRate = ReadFloat(data, ref pos); break;
					case 12 when wire == 0: s.Channels = (int)ReadVarint(data, ref pos); break;
					case 13 when wire == 2: s.HdrFormat = ReadString(data, ref pos); break;
					default: SkipField(data, ref pos, wire); break;
				}
			}
			return s;
		}

		// ── protobuf-net bcl.proto surrogates ────────────────────────────────
		// DateTime/TimeSpan { 1: sint64 value, 2: TimeScale scale } where value is
		// expressed in 'scale' units (DateTime: offset from 1970-01-01). MinMax scale
		// encodes MinValue (-1) and MaxValue (+1).

		enum TimeScale { Days = 0, Hours = 1, Minutes = 2, Seconds = 3, Milliseconds = 4, Ticks = 5, MinMax = 15 }

		static readonly DateTime Epoch = new(1970, 1, 1);

		static DateTime ReadBclDateTime(ReadOnlySpan<byte> data) {
			var (value, scale) = ReadBclTimeMessage(data);
			if (scale == TimeScale.MinMax)
				return value >= 0 ? DateTime.MaxValue : DateTime.MinValue;
			return Epoch.AddTicks(ToTicks(value, scale));
		}

		static TimeSpan ReadBclTimeSpan(ReadOnlySpan<byte> data) {
			var (value, scale) = ReadBclTimeMessage(data);
			if (scale == TimeScale.MinMax)
				return value >= 0 ? TimeSpan.MaxValue : TimeSpan.MinValue;
			return TimeSpan.FromTicks(ToTicks(value, scale));
		}

		static long ToTicks(long value, TimeScale scale) => scale switch {
			TimeScale.Days => value * TimeSpan.TicksPerDay,
			TimeScale.Hours => value * TimeSpan.TicksPerHour,
			TimeScale.Minutes => value * TimeSpan.TicksPerMinute,
			TimeScale.Seconds => value * TimeSpan.TicksPerSecond,
			TimeScale.Milliseconds => value * TimeSpan.TicksPerMillisecond,
			TimeScale.Ticks => value,
			_ => throw new InvalidDataException($"Unsupported time scale {scale} in legacy database.")
		};

		static (long value, TimeScale scale) ReadBclTimeMessage(ReadOnlySpan<byte> data) {
			long value = 0;
			TimeScale scale = TimeScale.Days;
			int pos = 0;
			while (pos < data.Length) {
				ulong tag = ReadVarint(data, ref pos);
				int field = (int)(tag >> 3);
				int wire = (int)(tag & 7);
				if (field == 1 && wire == 0)
					value = DecodeZigZag(ReadVarint(data, ref pos));
				else if (field == 2 && wire == 0)
					scale = (TimeScale)ReadVarint(data, ref pos);
				else
					SkipField(data, ref pos, wire); // field 3 = DateTimeKind, intentionally ignored (ticks-only equality)
			}
			return (value, scale);
		}

		// ── primitive wire format ─────────────────────────────────────────────

		static ulong ReadVarint(ReadOnlySpan<byte> data, ref int pos) {
			ulong result = 0;
			int shift = 0;
			while (true) {
				if (pos >= data.Length)
					throw new InvalidDataException("Truncated varint in legacy database.");
				byte b = data[pos++];
				result |= (ulong)(b & 0x7F) << shift;
				if ((b & 0x80) == 0)
					return result;
				shift += 7;
				if (shift >= 70)
					throw new InvalidDataException("Malformed varint in legacy database.");
			}
		}

		static long DecodeZigZag(ulong value) => (long)(value >> 1) ^ -(long)(value & 1);

		static ReadOnlySpan<byte> ReadLengthDelimited(ReadOnlySpan<byte> data, ref int pos) {
			int len = checked((int)ReadVarint(data, ref pos));
			if (len < 0 || pos + len > data.Length)
				throw new InvalidDataException("Truncated length-delimited field in legacy database.");
			var slice = data.Slice(pos, len);
			pos += len;
			return slice;
		}

		static string ReadString(ReadOnlySpan<byte> data, ref int pos) =>
			Encoding.UTF8.GetString(ReadLengthDelimited(data, ref pos));

		static double ReadDouble(ReadOnlySpan<byte> data, ref int pos) =>
			BitConverter.Int64BitsToDouble((long)ReadFixed64(data, ref pos));

		static float ReadFloat(ReadOnlySpan<byte> data, ref int pos) {
			if (pos + 4 > data.Length)
				throw new InvalidDataException("Truncated fixed32 in legacy database.");
			float f = BitConverter.Int32BitsToSingle(BinaryPrimitives.ReadInt32LittleEndian(data.Slice(pos, 4)));
			pos += 4;
			return f;
		}

		static ulong ReadFixed64(ReadOnlySpan<byte> data, ref int pos) {
			if (pos + 8 > data.Length)
				throw new InvalidDataException("Truncated fixed64 in legacy database.");
			ulong v = BinaryPrimitives.ReadUInt64LittleEndian(data.Slice(pos, 8));
			pos += 8;
			return v;
		}

		static void SkipField(ReadOnlySpan<byte> data, ref int pos, int wireType) {
			switch (wireType) {
				case 0: ReadVarint(data, ref pos); break;
				case 1: pos += 8; break;
				case 2: ReadLengthDelimited(data, ref pos); break;
				case 5: pos += 4; break;
				default: throw new InvalidDataException($"Unsupported wire type {wireType} in legacy database.");
			}
			if (pos > data.Length)
				throw new InvalidDataException("Truncated field in legacy database.");
		}

		static uint[] Append(uint[]? array, uint value) {
			if (array == null) return new[] { value };
			var bigger = new uint[array.Length + 1];
			array.CopyTo(bigger, 0);
			bigger[^1] = value;
			return bigger;
		}

		static uint[] Concat(uint[] array, List<uint> extra) {
			var bigger = new uint[array.Length + extra.Count];
			array.CopyTo(bigger, 0);
			extra.CopyTo(bigger, array.Length);
			return bigger;
		}
	}
}
