//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoDuplicateFinder.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoDuplicateFinder.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string CleaningUp {
            get {
                return ResourceManager.GetString("CleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string CopyingFiles {
            get {
                return ResourceManager.GetString("CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Log To Clipboard.
        /// </summary>
        public static string CopyLogToClipboard {
            get {
                return ResourceManager.GetString("CopyLogToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Folder (Keep Files).
        /// </summary>
        public static string CopyToFolderKeepFiles {
            get {
                return ResourceManager.GetString("CopyToFolderKeepFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all checked items from DISK (to recycle bin if possible)?.
        /// </summary>
        public static string DeleteAllCheckedItemsFromDISKToRecycleBinIfPossible {
            get {
                return ResourceManager.GetString("DeleteAllCheckedItemsFromDISKToRecycleBinIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Checked.
        /// </summary>
        public static string DeleteChecked {
            get {
                return ResourceManager.GetString("DeleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        public static string DeleteSelection {
            get {
                return ResourceManager.GetString("DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates In List: .
        /// </summary>
        public static string DuplicatesInList {
            get {
                return ResourceManager.GetString("DuplicatesInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: .
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating input folders....
        /// </summary>
        public static string EnumeratingInputFolders {
            get {
                return ResourceManager.GetString("EnumeratingInputFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Directories.
        /// </summary>
        public static string ExcludeDirectories {
            get {
                return ResourceManager.GetString("ExcludeDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy some files. Please check log!.
        /// </summary>
        public static string FailedToCopySomeFilesPleaseCheckLog {
            get {
                return ResourceManager.GetString("FailedToCopySomeFilesPleaseCheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg.exe / FFprobe.exe is missing. Please make sure both are placed in the same directory as this application..
        /// </summary>
        public static string FFmpegExeFFprobeExeIsMissing {
            get {
                return ResourceManager.GetString("FFmpegExeFFprobeExeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FileTypeFilter_All {
            get {
                return ResourceManager.GetString("FileTypeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string FileTypeFilter_Images {
            get {
                return ResourceManager.GetString("FileTypeFilter_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string FileTypeFilter_Videos {
            get {
                return ResourceManager.GetString("FileTypeFilter_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From List (Keep Files).
        /// </summary>
        public static string FromListKeepFiles {
            get {
                return ResourceManager.GetString("FromListKeepFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Read Only Folders.
        /// </summary>
        public static string IgnoreReadOnlyFolders {
            get {
                return ResourceManager.GetString("IgnoreReadOnlyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Images.
        /// </summary>
        public static string IncludeImages {
            get {
                return ResourceManager.GetString("IncludeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Sub Directories.
        /// </summary>
        public static string IncludeSubDirectories {
            get {
                return ResourceManager.GetString("IncludeSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Folder.
        /// </summary>
        public static string MoveToFolder {
            get {
                return ResourceManager.GetString("MoveToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Folder.
        /// </summary>
        public static string OpenInFolder {
            get {
                return ResourceManager.GetString("OpenInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time: .
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Directories.
        /// </summary>
        public static string SearchDirectories {
            get {
                return ResourceManager.GetString("SearchDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 100% Identical Except Size (Keep Smallest).
        /// </summary>
        public static string Select100IdenticalExceptSizeKeepSmallest {
            get {
                return ResourceManager.GetString("Select100IdenticalExceptSizeKeepSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 100% Identical (Keep First).
        /// </summary>
        public static string Select100IdenticalKeepFirst {
            get {
                return ResourceManager.GetString("Select100IdenticalKeepFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lowest Duration / Lowest Quality (Keep longest / Best Quality).
        /// </summary>
        public static string SelectLowestDurationLowestQualityKeepLongestBestQuality {
            get {
                return ResourceManager.GetString("SelectLowestDurationLowestQualityKeepLongestBestQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created Ascending.
        /// </summary>
        public static string Sort_DateCreatedAscending {
            get {
                return ResourceManager.GetString("Sort_DateCreatedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created Descending.
        /// </summary>
        public static string Sort_DateCreatedDescending {
            get {
                return ResourceManager.GetString("Sort_DateCreatedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Ascending.
        /// </summary>
        public static string Sort_DurationAscending {
            get {
                return ResourceManager.GetString("Sort_DurationAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Descending.
        /// </summary>
        public static string Sort_DurationDescending {
            get {
                return ResourceManager.GetString("Sort_DurationDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Sort_None {
            get {
                return ResourceManager.GetString("Sort_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Ascending.
        /// </summary>
        public static string Sort_ResolutionAscending {
            get {
                return ResourceManager.GetString("Sort_ResolutionAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Descending.
        /// </summary>
        public static string Sort_ResolutionDescending {
            get {
                return ResourceManager.GetString("Sort_ResolutionDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Ascending.
        /// </summary>
        public static string Sort_SizeAscending {
            get {
                return ResourceManager.GetString("Sort_SizeAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Descending.
        /// </summary>
        public static string Sort_SizeDescending {
            get {
                return ResourceManager.GetString("Sort_SizeDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Html.
        /// </summary>
        public static string ToHtml {
            get {
                return ResourceManager.GetString("ToHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Recycle Bin.
        /// </summary>
        public static string ToRecycleBin {
            get {
                return ResourceManager.GetString("ToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duplicate Groups: .
        /// </summary>
        public static string TotalDuplicateGroups {
            get {
                return ResourceManager.GetString("TotalDuplicateGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duplicates: .
        /// </summary>
        public static string TotalDuplicates {
            get {
                return ResourceManager.GetString("TotalDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size: .
        /// </summary>
        public static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size Removed: .
        /// </summary>
        public static string TotalSizeRemoved {
            get {
                return ResourceManager.GetString("TotalSizeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
