//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateFinderEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuplicateFinderEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building file list....
        /// </summary>
        internal static string BuildingFileList {
            get {
                return ResourceManager.GetString("BuildingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation exception caught!.
        /// </summary>
        internal static string CancellationExceptionCaught {
            get {
                return ResourceManager.GetString("CancellationExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cleanup has finished in: {0}, {1} entries have been removed.
        /// </summary>
        internal static string DatabaseCleanupHasFinished {
            get {
                return ResourceManager.GetString("DatabaseCleanupHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates check finished in: {0}.
        /// </summary>
        internal static string DuplicatesCheckFinishedIn {
            get {
                return ResourceManager.GetString("DuplicatesCheckFinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy &apos;{0}&apos;, reason: Directory does not exist.
        /// </summary>
        internal static string FailedToCopyReasonDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("FailedToCopyReasonDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy &apos;{0}&apos; to &apos;{1}&apos;, reason: {2}.
        /// </summary>
        internal static string FailedToCopyToReason {
            get {
                return ResourceManager.GetString("FailedToCopyToReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg process is already started.
        /// </summary>
        internal static string FFMpegProcessIsAlreadyStarted {
            get {
                return ResourceManager.GetString("FFMpegProcessIsAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg process was aborted.
        /// </summary>
        internal static string FFMpegProcessWasAborted {
            get {
                return ResourceManager.GetString("FFMpegProcessWasAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg timeout. File: {0}.
        /// </summary>
        internal static string FFMpegTimeoutFile {
            get {
                return ResourceManager.GetString("FFMpegTimeoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFprobe error: {0}, File: {1}.
        /// </summary>
        internal static string FFprobeError {
            get {
                return ResourceManager.GetString("FFprobeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (exit code: {1}).
        /// </summary>
        internal static string FFProbeException {
            get {
                return ResourceManager.GetString("FFProbeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFProbe process exceeded execution timeout ({0}) and was aborted, File: {1}.
        /// </summary>
        internal static string FFProbeProcessExceededExecutionTimeout {
            get {
                return ResourceManager.GetString("FFProbeProcessExceededExecutionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFprobe process was aborted.
        /// </summary>
        internal static string FFprobeProcessWasAborted {
            get {
                return ResourceManager.GetString("FFprobeProcessWasAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished building file list in {0}.
        /// </summary>
        internal static string FinishedBuildingFileListIn {
            get {
                return ResourceManager.GetString("FinishedBuildingFileListIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found previously scanned files, importing....
        /// </summary>
        internal static string FoundPreviouslyScannedFilesImporting {
            get {
                return ResourceManager.GetString("FoundPreviouslyScannedFilesImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously scanned files imported. {0:N0} files in {1}.
        /// </summary>
        internal static string PreviouslyScannedFilesImported {
            get {
                return ResourceManager.GetString("PreviouslyScannedFilesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scanned files to disk ({0:N0} files)..
        /// </summary>
        internal static string SaveScannedFilesToDisk0N0Files {
            get {
                return ResourceManager.GetString("SaveScannedFilesToDisk0N0Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan done.
        /// </summary>
        internal static string ScanDone {
            get {
                return ResourceManager.GetString("ScanDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan paused.
        /// </summary>
        internal static string ScanPaused {
            get {
                return ResourceManager.GetString("ScanPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan resumed.
        /// </summary>
        internal static string ScanResumed {
            get {
                return ResourceManager.GetString("ScanResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan stopped.
        /// </summary>
        internal static string ScanStopped {
            get {
                return ResourceManager.GetString("ScanStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped (blacklist): {0}.
        /// </summary>
        internal static string SkippedBlacklist {
            get {
                return ResourceManager.GetString("SkippedBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped (error): {0}, reason: {1}.
        /// </summary>
        internal static string SkippedErrorReason {
            get {
                return ResourceManager.GetString("SkippedErrorReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped (readonly): {0}.
        /// </summary>
        internal static string SkippedReadonly {
            get {
                return ResourceManager.GetString("SkippedReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scan.
        /// </summary>
        internal static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails finished in: {0}, processed files: {1:N0}.
        /// </summary>
        internal static string ThumbnailsFinished {
            get {
                return ResourceManager.GetString("ThumbnailsFinished", resourceCulture);
            }
        }
    }
}
