// /*
//     Copyright (C) 2026 0x90d
//     This file is part of VideoDuplicateFinder
//     VideoDuplicateFinder is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//     VideoDuplicateFinder is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
//     You should have received a copy of the GNU Affero General Public License
//     along with VideoDuplicateFinder.  If not, see <http://www.gnu.org/licenses/>.
// */
//

using MemoryPack;
using VDF.Core.Utils;

namespace VDF.Core.Tests.Utils;

/// <summary>
/// Covers the database format split: LegacyDatabaseReader must decode protobuf-net
/// files exactly (golden fixtures in TestAssets were generated BY protobuf-net
/// itself before the dependency was removed), and the MemoryPack format must
/// round-trip losslessly.
/// </summary>
public class DatabaseFormatTests {
	static string Asset(string name) =>
		Path.Combine(AppContext.BaseDirectory, "TestAssets", name);

	static FileEntry EntryByPath(DatabaseWrapper wrapper, string pathSuffix) =>
		wrapper.Entries.Single(e => e.Path.EndsWith(pathSuffix, StringComparison.OrdinalIgnoreCase));

	[Fact]
	public void LegacyReader_DecodesWrapperFixture_AllFields() {
		var wrapper = LegacyDatabaseReader.Read(File.ReadAllBytes(Asset("legacy-wrapper.db")));

		Assert.Equal(3, wrapper.Version);
		Assert.Equal(1, wrapper.ImageHashPipeline);
		Assert.Equal(3, wrapper.Entries.Count);

		var a = EntryByPath(wrapper, "movie.mp4");
		Assert.Equal(@"C:\vids\ä 🎬 movie.mp4", a.Path);
		Assert.Equal(@"C:\vids", a.Folder);
		Assert.Equal(123_456_789_012, a.FileSize);
		Assert.Equal(new DateTime(2023, 8, 15, 12, 34, 56, 789), a.DateCreated);
		Assert.Equal(new DateTime(2024, 1, 2, 3, 4, 5), a.DateModified);
		Assert.Equal(EntryFlags.NoAudioTrack | EntryFlags.TooDark, a.Flags);
		Assert.Equal(new uint[] { 0u, 1u, uint.MaxValue, 12345u }, a.AudioFingerprint);
		// grayBytes: one stored pattern
		var gray = Assert.Single(a.grayBytes);
		Assert.Equal(12.5, gray.Key);
		Assert.NotNull(gray.Value);
		Assert.Equal(1024, gray.Value!.Length);
		for (int i = 0; i < 1024; i++)
			Assert.Equal((byte)(i * 7), gray.Value[i]);
		// PHashes: one real, one stored-null (#754-era databases)
		Assert.Equal(2, a.PHashes.Count);
		Assert.Equal(0xDEADBEEFCAFEBABEUL, a.PHashes[12.5]);
		Assert.Null(a.PHashes[25.0]);
		// MediaInfo
		Assert.NotNull(a.mediaInfo);
		Assert.Equal(new TimeSpan(0, 1, 23, 45, 678), a.mediaInfo!.Duration);
		Assert.Equal(2, a.mediaInfo.Streams.Length);
		var v = a.mediaInfo.Streams[0];
		Assert.Equal("h264", v.CodecName);
		Assert.Equal("H.264 / AVC", v.CodecLongName);
		Assert.Equal("video", v.CodecType);
		Assert.Equal("yuv420p", v.PixelFormat);
		Assert.Equal(1920, v.Width);
		Assert.Equal(1080, v.Height);
		Assert.Equal(4_500_000, v.BitRate);
		Assert.Equal(29.97f, v.FrameRate);
		Assert.Equal("HDR10", v.HdrFormat);
		var au = a.mediaInfo.Streams[1];
		Assert.Equal("aac", au.CodecName);
		Assert.Equal(48000, au.SampleRate);
		Assert.Equal("stereo", au.ChannelLayout);
		Assert.Equal(2, au.Channels);

		var b = EntryByPath(wrapper, "photo.jpg");
		Assert.True(b.Flags.Has(EntryFlags.IsImage));
		Assert.Equal(4096, b.FileSize);
		// Empty arrays are wire-indistinguishable from absent repeated fields in
		// protobuf, so protobuf-net itself round-tripped Array.Empty as null too.
		// Harmless: the NoAudioTrack flag short-circuits before the null check.
		Assert.Null(b.AudioFingerprint);
		Assert.Equal(256, b.grayBytes[0]!.Length);
		Assert.Equal(640, b.mediaInfo!.Streams[0].Width);
		Assert.Equal(480, b.mediaInfo.Streams[0].Height);
		Assert.Equal(TimeSpan.Zero, b.mediaInfo.Duration);

		var c = EntryByPath(wrapper, "minimal.mkv");
		Assert.Equal(@"C:\server\share\minimal.mkv", c.Path);
		Assert.Equal(0, c.FileSize);
		Assert.Equal(DateTime.MinValue, c.DateCreated);
		Assert.Equal(DateTime.MaxValue, c.DateModified);
		Assert.Equal((EntryFlags)0, c.Flags);
		Assert.Null(c.AudioFingerprint);
		Assert.Null(c.mediaInfo);
		Assert.Empty(c.grayBytes);
		Assert.Empty(c.PHashes);
	}

	[Fact]
	public void LegacyReader_DecodesAncientBareHashSetFixture() {
		var wrapper = LegacyDatabaseReader.Read(File.ReadAllBytes(Asset("legacy-barehashset.db")));

		var entry = Assert.Single(wrapper.Entries);
		Assert.Equal(@"C:\vids\ä 🎬 movie.mp4", entry.Path);
		Assert.Equal(123_456_789_012, entry.FileSize);
		Assert.Equal(1024, entry.grayBytes[12.5]!.Length);
	}

	[Theory]
	[InlineData(new byte[0])]
	[InlineData(new byte[] { 0xFF, 0xFF, 0xFF, 0xFF })]
	public void LegacyReader_GarbageInput_DoesNotReturnPhantomEntries(byte[] data) {
		try {
			var wrapper = LegacyDatabaseReader.Read(data);
			Assert.Empty(wrapper.Entries);
		}
		catch (InvalidDataException) {
			// also acceptable — caller quarantines the file
		}
	}

	[Fact]
	public void MemoryPack_RoundTrip_IsLossless() {
		// Reuse the golden fixture as a rich, realistic object graph.
		var original = LegacyDatabaseReader.Read(File.ReadAllBytes(Asset("legacy-wrapper.db")));

		byte[] bin = MemoryPackSerializer.Serialize(original);
		var restored = MemoryPackSerializer.Deserialize<DatabaseWrapper>(bin)!;

		Assert.Equal(original.Version, restored.Version);
		Assert.Equal(original.ImageHashPipeline, restored.ImageHashPipeline);
		Assert.Equal(original.Entries.Count, restored.Entries.Count);
		foreach (var entry in original.Entries) {
			var other = EntryByPath(restored, Path.GetFileName(entry.Path));
			Assert.Equal(entry.Path, other.Path);
			Assert.Equal(entry.Folder, other.Folder);
			Assert.Equal(entry.FileSize, other.FileSize);
			Assert.Equal(entry.DateCreated, other.DateCreated);
			Assert.Equal(entry.DateModified, other.DateModified);
			Assert.Equal(entry.Flags, other.Flags);
			Assert.Equal(entry.AudioFingerprint, other.AudioFingerprint);
			Assert.Equal(entry.grayBytes.Count, other.grayBytes.Count);
			foreach (var (key, value) in entry.grayBytes)
				Assert.Equal(value, other.grayBytes[key]);
			Assert.Equal(entry.PHashes.Count, other.PHashes.Count);
			foreach (var (key, value) in entry.PHashes)
				Assert.Equal(value, other.PHashes[key]);
			Assert.Equal(entry.mediaInfo?.Duration, other.mediaInfo?.Duration);
			Assert.Equal(entry.mediaInfo?.Streams?.Length, other.mediaInfo?.Streams?.Length);
		}
	}

	[Fact]
	public void DatabaseUtils_MigratesLegacyFileToNewFormat() {
		string dir = Path.Combine(Path.GetTempPath(), $"vdf-dbmig-{Guid.NewGuid():N}");
		Directory.CreateDirectory(dir);
		try {
			File.Copy(Asset("legacy-wrapper.db"), Path.Combine(dir, "ScannedFiles.db"));

			DatabaseUtils.CustomDatabaseFolder = dir;
			DatabaseUtils.InvalidateDatabaseFolder();

			Assert.True(DatabaseUtils.LoadDatabase());
			Assert.Equal(3, DatabaseUtils.Database.Count);

			DatabaseUtils.SaveDatabase();

			// File now starts with the new-format magic …
			byte[] header = new byte[8];
			using (var fs = File.OpenRead(Path.Combine(dir, "ScannedFiles.db")))
				fs.ReadExactly(header);
			Assert.Equal("VDFDB001"u8.ToArray(), header);

			// … and loads back with identical content.
			Assert.True(DatabaseUtils.LoadDatabase());
			Assert.Equal(3, DatabaseUtils.Database.Count);
			var a = DatabaseUtils.Database.Single(e => e.Path.EndsWith("movie.mp4"));
			Assert.Equal(0xDEADBEEFCAFEBABEUL, a.PHashes[12.5]);
			Assert.Equal(1024, a.grayBytes[12.5]!.Length);
		}
		finally {
			DatabaseUtils.CustomDatabaseFolder = null;
			DatabaseUtils.InvalidateDatabaseFolder();
			DatabaseUtils.Database.Clear();
			try { Directory.Delete(dir, recursive: true); } catch { }
		}
	}
}
