name: Build releases


on: [push]
    
jobs:
  build:

    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            name: linux-x64
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            singlefile: true
          - kind: windows
            os: windows-latest
            target: win-x64
            name: win-x64
          - kind: windows
            os: windows-latest
            target: win-x64
            singlefile: true
          - kind: macOS
            os: windows-latest
            target: osx-x64
            name: osx-x64
          - kind: macOS
            os: windows-latest
            target: osx-x64
            singlefile: true
            
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Declare some variables
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build
      shell: bash
      run: |
          if [ "${{ matrix.singlefile }}" == "true" ]; then
            release_name="App-${{ matrix.target }}-singlefile"
          else
            release_name="App-${{ matrix.target }}"
          # Add nuget sources
          dotnet nuget add source https://www.myget.org/F/sixlabors/api/v3/index.json
          # Build everything
          if [ "${{ matrix.singlefile }}" == "true" ]; then
            dotnet publish -c Release -v q -p:PublishSingleFile=true --self-contained -r "${{ matrix.target }}" -o "outputFolder"
          else
            dotnet publish -c Release -v q --self-contained -r "${{ matrix.target }}" -o "outputFolder"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./outputFolder/*"
          else
            tar czvf "${release_name}.tar.gz" "outputFolder"
          fi
          # Delete output directory
          rm -r "outputFolder"
          
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
          tag_name: 3.0.x
          files: App*
          prerelease: true
          body: |
            Note: These are daily builds. Attachments are automatically created and replaced on every new commit. Regardless of what the message above says. If you experience upgrade issues you may need to delete your 'ScannedFiles.db' file in VDF folder.
            Last build based on ${{ steps.vars.outputs.sha_short }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


